#!/usr/bin/env bash

usage () {
cat << EOD
Usage: kube-get-versions QA expected.txt

QA: Kubernetes namespace (Required)
expected.txt: Output filename

EOD

exit 0
}

program_exists() {
    local ret='0'
    command -v $1 >/dev/null 2>&1 || { local ret='1'; }

    # fail on non-zero return value
    if [ "$ret" -ne 0 ]; then
        return 1
    fi

    return 0
}

program_must_exist() {
    program_exists $1

    # throw error on non-zero return value
    if [ "$?" -ne 0 ]; then
        error "You must have '$1' installed to continue."
    fi
}


program_must_exist kubectl


if [[ -z $1 ]]; then
    usage
fi


NAMESPACE=$1
FILENAME=$2

if [[ -z $NAMESPACE ]]; then
    echo -e "Namespace required"
    exit 1
fi


if [[ -z $FILENAME ]]; then
    echo -e "Filename is required"
    exit 1
fi

kubectl describe deployments -n "$NAMESPACE" | grep Image > "$FILENAME"

echo  'Wrote' "$FILENAME"
