#!/usr/bin/env bash


usage () {
cat << EOD
Usage: kube-get-version QA admin

QA: Kubernetes namespace (Required)
Search string: Name of the service or image

EOD

exit 0
}

program_exists() {
    local ret='0'
    command -v $1 >/dev/null 2>&1 || { local ret='1'; }

    # fail on non-zero return value
    if [ "$ret" -ne 0 ]; then
        return 1
    fi

    return 0
}

program_must_exist() {
    program_exists $1

    # throw error on non-zero return value
    if [ "$?" -ne 0 ]; then
        error "You must have '$1' installed to continue."
    fi
}


program_must_exist kubectl

NAMESPACE=$1
SERVICE=$2

if [[ -z $1 ]]; then
    usage
fi

if [[ -z $NAMESPACE ]]; then
    echo -e "Namespace required"
    exit 1
fi


if [[ -z $SERVICE ]]; then
    echo -e "Service is required"
    exit 1
fi

kubectl describe deployment -n "$NAMESPACE"| grep Image | grep -i "$SERVICE"
