#!/usr/bin/env bash

usage() {
cat <<HERE
usage: kubectl-change-namespace $ENVIRONMENT

If nothing is passed as an environment the available contexts will be shown.
HERE
}

if [[ -z $1 ]]; then
    #statements
    kubectl config get-contexts
    exit 1
fi

kubectl config set-context `kubectl config current-context` --namespace $1
