#!/usr/bin/env bash

usage () {
cat << EOD
Usage: kubectl-get-podname QA admin



QA: Kubernetes namespace (Required)
Admin: Partial name of the pod

EOD

exit 0
}

NAMESPACE=$1
PARTIALPODNAME=$2

if [[ $NAMESPACE = 'h' ]]; then
    #statements
    usage
fi

if [[ -z $NAMESPACE ]]; then
    echo -e "Namespace required"
    exit 1
fi


if [[ -z $PARTIALPODNAME ]]; then
    echo -e "Partial pod name is required"
    exit 1
fi

kubectl get pods -n $1 | grep $2 | awk -F ' ' '{print $1}'
